# Generated by Django 6.0.3 on 2026-04-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_pending_sd_and_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('PENDING_HEAD', 'Pending Head'), ('PENDING_HR', 'Pending HR'), ('PENDING_SD', 'Pending SD'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_HEAD', max_length=50),
        ),
    ]
