# Generated by Django 6.0.3 on 2026-04-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_groups_alter_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='can_self_upload',
            field=models.BooleanField(default=False),
        ),
    ]
