# Generated by Django 6.0.3 on 2026-04-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20260412_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('CIVIL', 'Civil Engineering'), ('COMP_ENG', 'Computer Engineering'), ('ELEC', 'Electrical Engineering'), ('IND_ENG', 'Industrial Engineering'), ('MECH', 'Mechanical Engineering'), ('IT', 'Information Technology'), ('CS', 'Computer Science'), ('EMC', 'Entertainment & Multimedia Computing'), ('NURSING', 'Nursing'), ('MED_TECH', 'Medical Technology'), ('PHARMA', 'Pharmacy'), ('CBA', 'Business Administration'), ('CRIM', 'Criminology'), ('EDUC', 'Education'), ('IHM', 'International Hospitality Management')], max_length=50, unique=True),
        ),
    ]
