# Generated by Django 6.0.3 on 2026-04-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='trainer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
